Task 1 take a 5x5 matrix using np.one method and print array like
[[1 1 1 1 1],
 [1 0 0 0 1],
 [1 0 9 0 1],
 [1 0 0 0 1],
 [1 1 1 1 1]]

In [1]:
import numpy as np

In [2]:
a = np.ones((5,5), dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [3]:
a[1:4, 1:4] = 0
a[2,2] = 9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


task 2 
[[1  2  3  4  5]
 [6  7  8  9  10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
  output [[2 8 14 20]]

In [4]:
b = np.arange(1,26).reshape((5,5))
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [5]:
"""c = np.array([b[0,1], b[1,2], b[2,3], b[3,4]])
print(c)"""
print(b[[0,1,2,3], [1,2,3,4]])


[ 2  8 14 20]


task 2 
[[1  2  3  4  5]
 [6  7  8  9  10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 output [[4  5]
         [19 20]
         [24 25]]

In [6]:
print(b[[0,3,4],3:5])

[[ 4  5]
 [19 20]
 [24 25]]


In [7]:
c = np.eye(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
