In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [3]:
a1 = a.flatten()
print(a1)
print(a1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [4]:
x1 = np.arange(24).reshape(4,3,2)
print(x1)
print(x1.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)


In [5]:
b2 = x1.flatten()
print(b2)
print(b2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [6]:
x3 = np.arange(12).reshape(4,3)
print(x3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
b3 = x3.flatten(order='F')
print(b3)
print(b3.shape)

[ 0  3  6  9  1  4  7 10  2  5  8 11]
(12,)


In [8]:
b4 = x3.flatten(order='C')
print(b4)
print(b4.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [9]:
b4 = x3.flatten(order='K')
print(b4)
print(b4.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
