In [1]:
import numpy as np

In [2]:
x = np.array([10,20,30,40,50,60])
print(x)

[10 20 30 40 50 60]


In [3]:
x = np.array([[10,20,30],[40,50,60]])
print(x)

[[10 20 30]
 [40 50 60]]


In [4]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
x = np.zeros([2,3],dtype=int)
print(x)

[[0 0 0]
 [0 0 0]]


In [7]:
x = np.full(5,8)
print(x)

[8 8 8 8 8]


In [8]:
x = np.full((5,2),8)
print(x)

[[8 8]
 [8 8]
 [8 8]
 [8 8]
 [8 8]]


In [9]:
x = np.arange(1,30)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [10]:
x = np.empty((20,10))
print(x)

[[6.95193697e-310 1.26053472e-311 1.26052609e-311 1.26049600e-311
  1.26052610e-311 1.26052610e-311 1.26052610e-311 1.26052610e-311
  1.26052610e-311 1.26052610e-311]
 [1.26052610e-311 1.26052610e-311 1.26052610e-311 6.95193702e-310
  6.95193702e-310 1.26054445e-311 1.26052610e-311 1.26049439e-311
  1.26052610e-311 1.26052610e-311]
 [1.26052610e-311 1.26049451e-311 1.26049764e-311 1.26052609e-311
  1.26054151e-311 1.26054446e-311 1.26052609e-311 1.26052610e-311
  1.26052205e-311 1.26052610e-311]
 [6.95193702e-310 6.95193702e-310 1.26052611e-311 1.26079470e-311
  1.26052610e-311 1.26049764e-311 1.26052581e-311 6.95193702e-310
  1.26079508e-311 1.26079508e-311]
 [6.95193702e-310 1.26079507e-311 1.26079510e-311 1.26079507e-311
  6.95193702e-310 1.26053714e-311 6.95193702e-310 1.26079480e-311
  1.26079508e-311 1.26079508e-311]
 [1.26051688e-311 1.26049600e-311 6.95193702e-310 6.95193702e-310
  6.95193702e-310 6.95193702e-310 1.26052581e-311 1.26049571e-311
  1.26049440e-311 1.26079508e-311

In [11]:
x = np.empty((10))
print(x)

[4.e-323 4.e-323 4.e-323 4.e-323 4.e-323 4.e-323 4.e-323 4.e-323 4.e-323
 4.e-323]


In [12]:
x = np.array([[10,20,30],[40,50,60]])
print(x)
print(x.shape)
x = np.array([[10,20,30]])
print(x)
print(x.shape)

[[10 20 30]
 [40 50 60]]
(2, 3)
[[10 20 30]]
(1, 3)


In [13]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)

[5 7 9]


x+y '+' operator provide sum index by index

In [14]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])
print(x+y)


[[ 2  4  6]
 [ 8 10 12]]


In [15]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x-y)

[-3 -3 -3]


In [16]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])
print(x-y)

[[0 0 0]
 [0 0 0]]


In [17]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x*y)

[ 4 10 18]


In [18]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])
print(x*y)

[[ 1  4  9]
 [16 25 36]]


In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x/y)

[0.25 0.4  0.5 ]


In [20]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])
print(x/y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
x = np.array([1,2,3])
y = np.array([4,5,6])
ans = np.sum(x+y)
print(ans)

21


use sum to get cumulative sum of all variable

In [22]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])
ans = np.sum(x+y)
print(ans)

42


In [23]:
x = np.arange(1,10)
print(x)
ans = np.sum(x)
print(ans)

[1 2 3 4 5 6 7 8 9]
45


while using sum in 2 arrays both array must have same length/dimention

In [24]:
x = np.arange(1,11)
y = np.arange(11,21)
ans = np.sum(x+y)
print(ans)

210


In [25]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
ans = np.sum(x)
print(ans)

45


In [27]:
ans = np.sum(x, axis=1)#for row wise addition
print(ans)

[ 6 15 24]


In [28]:
ans = np.sum(x, axis=0)#for column wise addidtion
print(ans)

[12 15 18]


important functions in numpy

In [29]:
x = np.array([10,11,23,45,67,86,56])
ans = np.mean(x)
print(ans)

42.57142857142857


In [30]:
x = np.array([10,11,23,45,67,86])
ans = np.median(x)
print(ans)

34.0


In [31]:
x = np.array([10,11,23,45,45,67,86])
ans = np.std(x)
print(ans)

26.50606399621469


In [32]:
ans2 = np.max(x)
ans3 = np.min(x)
print(ans2)
print(ans3)

86
10


In [33]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
ans = np.min(x, axis=1)
print(ans)

[1 4 7]


In [34]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
ans = np.min(x, axis=0)
print(ans)

[1 2 3]


In [35]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
ans = np.max(x, axis=1)
print(ans)

[3 6 9]


In [36]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
ans = np.max(x, axis=0)
print(ans)

[7 8 9]
