In [1]:
import random as r
import numpy as np

In [2]:
print(r.random())# number between 0 and 1 1 excluded

0.7781257522142521


In [3]:
print(r.randrange(1,10,2))# odd numbers between 1 and 10 taking step 2 excluding 10

3


In [4]:
print(r.randint(1,10))# number between 1 and 10 both included

9


In [5]:
a = np.random.randint(-10,10,12).reshape(3,4)#random values between -10 and 10 in 3x4 matrix
print(a)

[[-10  -2   2   6]
 [ -3   8  -8  -4]
 [ -6   3  -5   2]]


In [6]:
b = np.random.random((3,4))# random values between 0 and 1 in 3x4 matrix
print(b)

[[0.81946896 0.17472078 0.43248239 0.54923381]
 [0.25481223 0.94894501 0.91096015 0.46824066]
 [0.89003656 0.49730545 0.19376976 0.20901986]]


In [7]:
a = np.array([[10,2,34],[45,67,89],[15,17,99]])
print(a)
print(a.min())
print(a.max())

[[10  2 34]
 [45 67 89]
 [15 17 99]]
2
99


In [8]:
print(a.argmin())#index of min value
print(a.argmax())#index of max value

1
8


In [9]:
print(a.mean())
print(np.median(a))
print(a.std())

42.0
34.0
33.555923471125034


In [10]:
print(a.argmax(axis=0))#index of max value column wise
print(a.argmax(axis=1))#index of max value row wise
print(a.argmin(axis=0))#index of min value column wise
print(a.argmin(axis=1))#index of min value row wise

[1 1 2]
[2 2 2]
[0 0 0]
[1 0 0]


In [13]:
print(np.sort(a))# sort each row
print(np.argsort(a,axis=1))# indices that would sort each row
print(np.sort(a, axis=0))# sort each column
print(np.argsort(a,axis=0))# indices that would sort each column

[[ 2 10 34]
 [45 67 89]
 [15 17 99]]
[[1 0 2]
 [0 1 2]
 [0 1 2]]
[[10  2 34]
 [15 17 89]
 [45 67 99]]
[[0 0 0]
 [2 2 1]
 [1 1 2]]


In [16]:
a = np.arange(0,9).reshape((3,3))
b = np.arange(9,18).reshape((3,3))
result = np.dot(a,b)
print(result)
result = a.dot(b)
print(result)
result = np.matmul(a,b)
print(result)

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
