In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3,4,5,6])
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [3]:
a1 = a.reshape(2,3)
print(a1)
print(a1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [4]:
a2 = a.reshape(3,2)
print(a2)
print(a2.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [5]:
x = np.arange(12)
b = x.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
x2 = np.arange(12)
b2 = x2.reshape(-1,3)
print(b2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
