In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3,4,5,6,7,8,9,10])

In [3]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
print(arr[1])

2


In [5]:
print(arr[1:])

[ 2  3  4  5  6  7  8  9 10]


In [6]:
print(arr[:3])

[1 2 3]


In [7]:
print(arr[1:10])

[ 2  3  4  5  6  7  8  9 10]


In [8]:
print(arr[-1])

10


In [9]:
print(arr[:-1])

[1 2 3 4 5 6 7 8 9]


In [10]:
print(arr[-2:])

[ 9 10]


In [11]:
print(arr[0:10:2])

[1 3 5 7 9]


In [12]:
print(arr[::2])

[1 3 5 7 9]
