In [17]:
import numpy as np


In [18]:
x1 = np.array([
    [
        [1,  2,  3,  4],
        [5,  6,  7,  8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
x11 = np.array([
    [
        [1,  2,  3,  4],
        [5,  6,  7,  8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print("3D Array:")
print(x1)
print("Shape:", x1.shape)
print("Dimensions:", x1.ndim)

print("3D Array:")
print(x11)
print("Shape:", x11.shape)
print("Dimensions:", x11.ndim)

3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Dimensions: 3
3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Dimensions: 3


In [19]:
x2 = np.array([
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]
        ],
        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24]
        ]
    ],
    [
        [
            [25, 26, 27, 28],
            [29, 30, 31, 32],
            [33, 34, 35, 36]
        ],
        [
            [37, 38, 39, 40],
            [41, 42, 43, 44],
            [45, 46, 47, 48]
        ]
    ]
])
x22 = np.array([
    [
        [
            [1, 5, 3, 4],
            [5, 6, 9, 8],
            [9, 10, 11, 13]
        ],
        [
            [13, 18, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 28]
        ]
    ],
    [
        [
            [22, 26, 27, 28],
            [29, 34, 31, 32],
            [33, 34, 39, 36]
        ],
        [
            [37, 38, 39, 43],
            [41, 42, 44, 44],
            [45, 46, 47, 48]
        ]
    ]
])

print("4D Array:")
print(x2)
print("Shape:", x2.shape)
print("Dimensions:", x2.ndim)
print("4D Array:")
print(x22)
print("Shape:", x22.shape)
print("Dimensions:", x22.ndim)

4D Array:
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]]
Shape: (2, 2, 3, 4)
Dimensions: 4
4D Array:
[[[[ 1  5  3  4]
   [ 5  6  9  8]
   [ 9 10 11 13]]

  [[13 18 15 16]
   [17 18 19 20]
   [21 22 23 28]]]


 [[[22 26 27 28]
   [29 34 31 32]
   [33 34 39 36]]

  [[37 38 39 43]
   [41 42 44 44]
   [45 46 47 48]]]]
Shape: (2, 2, 3, 4)
Dimensions: 4


In [20]:
print(x1.shape)
print(x2.shape)
print(x11.shape)
print(x22.shape)

(2, 3, 4)
(2, 2, 3, 4)
(2, 3, 4)
(2, 2, 3, 4)


In [21]:
print(x1+x11)

[[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]]

 [[26 28 30 32]
  [34 36 38 40]
  [42 44 46 48]]]


In [22]:
print(x2+x22)

[[[[ 2  7  6  8]
   [10 12 16 16]
   [18 20 22 25]]

  [[26 32 30 32]
   [34 36 38 40]
   [42 44 46 52]]]


 [[[47 52 54 56]
   [58 64 62 64]
   [66 68 74 72]]

  [[74 76 78 83]
   [82 84 87 88]
   [90 92 94 96]]]]


In [23]:
print(x1-x11)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [24]:
print(x2-x22)

[[[[ 0 -3  0  0]
   [ 0  0 -2  0]
   [ 0  0  0 -1]]

  [[ 0 -4  0  0]
   [ 0  0  0  0]
   [ 0  0  0 -4]]]


 [[[ 3  0  0  0]
   [ 0 -4  0  0]
   [ 0  0 -4  0]]

  [[ 0  0  0 -3]
   [ 0  0 -1  0]
   [ 0  0  0  0]]]]


In [25]:
print(x1*x11)

[[[  1   4   9  16]
  [ 25  36  49  64]
  [ 81 100 121 144]]

 [[169 196 225 256]
  [289 324 361 400]
  [441 484 529 576]]]


In [26]:
print(x2*x22)

[[[[   1   10    9   16]
   [  25   36   63   64]
   [  81  100  121  156]]

  [[ 169  252  225  256]
   [ 289  324  361  400]
   [ 441  484  529  672]]]


 [[[ 550  676  729  784]
   [ 841 1020  961 1024]
   [1089 1156 1365 1296]]

  [[1369 1444 1521 1720]
   [1681 1764 1892 1936]
   [2025 2116 2209 2304]]]]


In [27]:
print(x1/x11)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [28]:
print(x2/x22)

[[[[1.         0.4        1.         1.        ]
   [1.         1.         0.77777778 1.        ]
   [1.         1.         1.         0.92307692]]

  [[1.         0.77777778 1.         1.        ]
   [1.         1.         1.         1.        ]
   [1.         1.         1.         0.85714286]]]


 [[[1.13636364 1.         1.         1.        ]
   [1.         0.88235294 1.         1.        ]
   [1.         1.         0.8974359  1.        ]]

  [[1.         1.         1.         0.93023256]
   [1.         1.         0.97727273 1.        ]
   [1.         1.         1.         1.        ]]]]


In [29]:
ans = np.sum(x1+x11)
print(ans)

600


In [30]:
ans = np.sum(x2+x22)
print(ans)

2375


In [31]:
ans = np.sum(x2)
print(ans)

1176


In [32]:
ans = np.sum(x1)
print(ans)

300


In [33]:
ans = np.sum(x11)
print(ans)

300


In [34]:
ans = np.sum(x22)
print(ans)

1199
