In [1]:
import numpy as np

In [2]:
# ans 1
arr1 = np.arange(1, 21)
print(arr1)
print(arr1.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20


In [3]:
#ans 2
zeros_array = np.zeros((3, 4))
ones_array = np.ones((2, 5))
print(zeros_array)
print(ones_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
#ans 3
full_array = np.full((4, 4), 7)
print(full_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [5]:
# ans 4
arr2 = np.arange(1, 13)
print(arr2.reshape(3, 4))
print(arr2.reshape(2, 6))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
# ans 5
mat3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat3.flatten())

[1 2 3 4 5 6 7 8 9]


In [7]:
# ans 6
arr3 = np.arange(10, 51, 5)
print(arr3)

[10 15 20 25 30 35 40 45 50]


In [8]:
# ans 7
arr4 = np.array([10, 20, 30, 40, 50])
print(np.sum(arr4))
print(np.sum(arr4[:3]))


150
60


In [9]:
# ans 8
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,5,4],[3,2,1]])
print(A + B)

[[7 7 7]
 [7 7 7]]


In [10]:
# ans 9
print(A - B)

[[-5 -3 -1]
 [ 1  3  5]]


In [11]:
# ans 10
print(A * B)

[[ 6 10 12]
 [12 10  6]]


In [12]:
# ans 11
arr5 = np.array([12, 15, 20, 25, 30])
print(np.mean(arr5))

20.4


In [13]:
# ans 12
arr6 = np.array([5, 2, 9, 1, 7, 6])
print(np.median(arr6))

5.5


In [14]:
# ans 13
arr7 = np.array([4, 8, 6, 5, 3, 7])
print(np.std(arr7))

1.707825127659933


In [15]:
# ans 14
mat4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(mat4, axis=1))

[ 6 15 24]


In [16]:
# ans 15
print(np.sum(mat4, axis=0))

[12 15 18]


In [17]:
# ans 16
arr8 = np.arange(1, 17).reshape(4, 4)
print(np.mean(arr8, axis=1))

[ 2.5  6.5 10.5 14.5]


In [18]:
# ans 17
ones5 = np.ones((5, 5))
flat = ones5.flatten()
print(flat.size)

25


In [19]:
# ans 18
A1 = np.array([1,2,3,4])
B1 = np.array([5,6,7,8])
print((A1 + B1) * 2)

[12 16 20 24]


In [20]:
# ans 19
arr9 = np.arange(1, 10).reshape(3, 3)
arr9 = arr9 * 5
print(np.sum(arr9))

225


In [21]:
# ans 20
arr10 = np.array([15, 18, 21, 24, 27, 30])
print(np.mean(arr10))
print(np.median(arr10))
print(np.std(arr10))

22.5
22.5
5.123475382979799


In [22]:
#ans 1
a = np.arange(1,49).reshape(4,4,3)
#b = a.reshape(4,4,3)
print(a)
#print(b)
#print(a.shape)
print(np.sum(a, axis=0))#block wise
print(np.sum(a, axis=1))#row wise
print(np.sum(a, axis=2))#column wise

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]
[[ 76  80  84]
 [ 88  92  96]
 [100 104 108]
 [112 116 120]]
[[ 22  26  30]
 [ 70  74  78]
 [118 122 126]
 [166 170 174]]
[[  6  15  24  33]
 [ 42  51  60  69]
 [ 78  87  96 105]
 [114 123 132 141]]


In [23]:
#ans 2
a1 = np.arange(1, 21)
a1 = np.where(a1 % 3 == 0 , -1 , a1)
a1 = np.where(a1 % 5 == 0 ,  100 , a1)
print(a1)

[  1   2  -1   4 100  -1   7   8  -1 100  11  -1  13  14  -1  16  17  -1
  19 100]


In [24]:
#ans 3
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([10,20,30])
C = A + B
print(C)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [25]:
#ans 4
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

flat2 = B.flatten()
flat2[0] = 999

print("\nFlattened (flatten) array:\n", flat2)
print("\nOriginal matrix after flatten modification:\n", B)



Flattened (flatten) array:
 [999   2   3   4   5   6   7   8   9]

Original matrix after flatten modification:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
#ans 5
a3 = np.arange(1,26).reshape(5,5)
print(a3)
print(a3[2])#middle row
print(a3[:,-1])#last column
print(a3[[0,-1,0,-1],[0,0,-1,-1]])#corners

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[11 12 13 14 15]
[ 5 10 15 20 25]
[ 1 21  5 25]


In [27]:
#ans 6
a4 = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(np.mean(a4,axis = 0))#mean
print(np.std(a4, axis = 1))#standard deviation

[40. 50. 60.]
[8.16496581 8.16496581 8.16496581]


In [28]:
#ans 7
A = np.random.randint(1, 10, (3,3))
B = np.random.randint(1, 10, (3,3))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
result = (A + B) * 2 - A
print("Result:\n", result)


Matrix A:
 [[2 7 9]
 [7 6 1]
 [5 1 9]]
Matrix B:
 [[8 9 9]
 [2 3 4]
 [8 2 1]]
Result:
 [[18 25 27]
 [11 12  9]
 [21  5 11]]


In [29]:
#ans 8
pattern = (np.indices((4,4)).sum(axis=0) % 2 == 0).astype(int)

print(pattern)

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


In [30]:
#ans 9
arr3d = np.arange(1, 28).reshape(3,3,3)

print("3D Array:\n", arr3d)

# Overall mean
overall_mean = np.mean(arr3d)

# Mean along axis 0
axis0_mean = np.mean(arr3d, axis=0)

# Median of entire array
median_all = np.median(arr3d)

print("\nOverall Mean:", overall_mean)
print("\nMean along axis 0:\n", axis0_mean)
print("\nMedian of entire array:", median_all)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Overall Mean: 14.0

Mean along axis 0:
 [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]

Median of entire array: 14.0


In [ ]:
# ans 10
arr = np.arange(1, 17)

arr2 = arr.reshape(4,4)
print( arr2)

mult = arr2 * np.array([1,2,3,4])
print("\nAfter column multiplication:\n", mult)

flat = mult.flatten()
print("\nFlattened array:\n", flat)

std_val = np.std(flat)
print("\nStandard Deviation:", std_val)

Reshaped 4x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

After column multiplication:
 [[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]
 [13 28 45 64]]

Flattened array:
 [ 1  4  9 16  5 12 21 32  9 20 33 48 13 28 45 64]

Standard Deviation: 17.38533865071371
